### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/ai-cli#2]
This document describes project roadmap. We plan to release v1.0 at some stage, when some of the features below are implemented. Since this is CLI tool the exact project version should not be as important as in the case of library projects.

## Inference providers

- [x] [OpenAI](https://platform.openai.com/docs/introduction)
- [x] [Antropic](https://docs.anthropic.com/claude/reference/getting-started-with-the-api)
- [x] [Perplexity](https://docs.perplexity.ai/docs/model-cards)
- [x] [Mistral AI](https://docs.mistral.ai/api/)
- [ ] [Gemini](https://ai.google.dev/)
- [ ] HuggingFace (?)

## Core features
- [x] `--model` option to select different models
- [x] `--provider` option to select different providers
- [x] Model parameter: system prompt
- [x] Creativity/precise/default response style option 
- [x] `ai init` command
- [x] `/save` command for saving current conversation
- [x] Upload text file for context (txt, markdown)

## Next steps
- [x] Migration to Ink
- [x] Streaming responses
- [x] [Antropic](https://docs.anthropic.com/claude/reference/getting-started-with-the-api)
- [x] Update notifier 
- [ ] Upload HTML files/URL for querying/summarization

## Other backlog
- [ ] Personas: create AI assistants for different use cases (e.g. JS, Python, etc)
- [ ] Model parameters: temperature, top_p, top_k
- [ ] Model parameters: context size
- [ ] Upload encoded text files for context (HTML, PDF, doc, etc)
- [ ] Upload image file for context
- [ ] Read context from URL ([this](https://github.com/mixmark-io/turndown) might help)
- [ ] Document summarization
- [ ] Query available models
- [ ] Local indexing database: adding and querying documents
- [ ] Save query history (optional)
- [ ] Generating images (DALL-E, etc)

**Comment by szymonrybczak** [comment]
@mdjastrzebski @Q1w1N did you consider streaming response from the external providers? 🤔
